### ISSUE TITLE
pod error

### ISSUE THREAD

**Issue by wxj1102** [LR-Studio/LRTextField#1]
minimum deployment target: 7.1

[!] Unable to satisfy the following requirements:
- `LRTextField (~> 1.1)` required by `Podfile`

Specs satisfying the `LRTextField (~> 1.1)` dependency were found, but they required a higher minimum deployment target.

**Comment by lc-git** [comment]
You need to update deployment target to 8.0 or 8.0+
The minimum deployment of LRSmartTextField is 8.0

**Comment by pc660** [comment]
The reason we need deployment version higher than 8.0 is that, we add ibdesignable feature in our variable.
If you do want your app supporting version less than 8.0, you can remove all those "@IBdesignable" and "@IBInspectable". I think that should do the trick.
