### ISSUE TITLE
More flexible

### ISSUE THREAD

**Issue by GuyKahlon** [LR-Studio/LRTextField#2]
In my opinion the properties:

@property (nonatomic, strong) UIColor *validationYesColor;
@property (nonatomic, strong) UIColor *validationNoColor;

Should be Public in order to make the library more flexible, and the colors will be controlled by the user (Green and Red are great default but is will by nice if the user can decide the color.)

Another great option to solve this issue, is to add more keys on the ValidationBlock, for example:

LRTextField *textFieldValidation = [[LRTextField alloc] initWithFrame:CGRectMake(20, 240, 260, 30) labelHeight:15];
    textFieldValidation.placeholder = @"Validation Demo";
    textFieldValidation.hintText = @"Enter \"abc\"";
    [textFieldValidation setValidationBlock:^NSDictionary *(LRTextField *textField, NSString *text) {
        [NSThread sleepForTimeInterval:1.0];
        if ([text isEqualToString:@"abc"]) {
            return @{ VALIDATION_INDICATOR_YES : @"Correct", VALIDATION_INDICATOR_YES_COLOR : UIColor.xxx() };
        }
        return @{ VALIDATION_INDICATOR_NO : @"Error" };
    }];
    [self.view addSubview:textFieldValidation];

BTW, Great work.

Guy

**Comment by pc660** [comment]
Thank you very much.
What you suggest is really valuable for us.  I guess the first option might be better because
it would be consistent with the ways we set the other properties(placeholder, hintText).

We will have an updated version for this issue pretty soon. :)

**Comment by GuyKahlon** [comment]
Thanks :)

**Comment by pc660** [comment]
Fixed.
