### ISSUE TITLE
Hint label won't show with layout constraints in storyboard.

### ISSUE THREAD

**Issue by vincilbishop** [LR-Studio/LRTextField#4]
I am having trouble getting the LRTextFieldStyleEmail to work in the storyboard. Is this something that can be set from storyboard, or must we instantiate the LRTextField in code to use default styles?

It looks like there is some incompatibility with layout constraints. Is anyone else using this library successfully with layout constraints?

**Comment by vincilbishop** [comment]
I was able to fix this by exposing the private method updateHint, then setting the .style property of the LRTextField, and calling updateHint in the viewDidLayoutSubviews method on the view controller. Still working out the kinks, but if anyone else has this issue, that might be a workaround. 

Nice library guys, thanks for the contribution...if I figure out a good packaged solution I'll give a pull request!

**Comment by pc660** [comment]
Thank you very much. Let me know if you have a pull request ready. 
We are also having a idea to use react.js to rewrite this library, this is very nice to aware that there might be some layout issues.
